### ISSUE TITLE
Note on comparisons

### ISSUE THREAD

**Issue by ngc5195bee** [maincold2/FFNeRV#1]
Hey. Great paper and exciting decode FPS results. However, I had two issues with your comparisons:

- Both HEVC and H.246 can run 4k decode at 120 FPS on a mobile. Ignoring their specialised hardware whilst you use a GPU seems unfair. 
- Your comparisons with other NN codecs should be updated. FVC is far from SOTA currently (e.g. see this https://arxiv.org/pdf/2207.05894.pdf). 

The work is suitably impressive despite it being quite a bit worse than SOTA neural codecs (they cannot run at nearly 60 FPS!)

**Comment by maincold2** [comment]
1) Since we thought it is needless to say that the commercial codecs are capable of fast decoding through hardware acceleration, we just evaluated them with CPU as in the NeRV paper. We agree with you that it can't be claimed FFNeRV shows faster decoding than the standard codecs. We would like to clarify this in the paper.
In terms of decoding speed, we want to emphasize that FFNeRV outperforms other neural codecs!

2) Although our curve slightly beats FVC, we didn't claim that our method is SOTA. We intended to show that our approach performs similarly to FVC, which is a recent and well-known neural codec. Please note that our method achieves SOTA compression performance among neural representations.

We appreciate your interest and thoughtful suggestions!

**Comment by ngc5195bee** [comment]
Thanks for the reply! I think this is valuable work and is likely an extension of the efficient frontier between performance and decode time. I hope you continue to improve 

On reflection, I think your codec is really random-access. Comparisons on both HEVC and NN are performed vs low-delay. HEVC, H.264 experience a 30% BD rate gain in random-access mode. That said, very few people publish NN random-access.
